include $(GOROOT)/src/Make.inc

TARG=oauth2_client_tester
GOFILES=\
    facebook.go\
    google.go\
    linkedin.go\
    twitter.go\
    yahoo.go\
    oauth2_client_tester.go\

include $(GOROOT)/src/Make.cmd
